# Generated by Django 6.0.1 on 2026-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('sys_admin', 'System Admin'), ('user', 'End User')], default='user', max_length=20),
        ),
    ]
