# Generated by Django 6.0.1 on 2026-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_tone',
            field=models.CharField(choices=[('casual', 'Casual'), ('academic', 'Academic'), ('storytelling', 'Storytelling')], default='casual', max_length=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='skip_visited_pois',
            field=models.BooleanField(default=True),
        ),
    ]
