# Generated by Django 6.0.1 on 2026-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.CharField(blank=True, choices=[('landmark', 'Landmark'), ('museum', 'Museum'), ('food', 'Food'), ('architecture', 'Architecture'), ('nature', 'Nature'), ('culture', 'Culture'), ('art', 'Art & Galleries'), ('religion', 'Religious Site'), ('shopping', 'Shopping & Markets'), ('nightlife', 'Nightlife & Bars'), ('sport', 'Sport & Stadiums'), ('viewpoint', 'Viewpoint & Panorama'), ('street_art', 'Street Art')], max_length=100, null=True),
        ),
    ]
